### ISSUE TITLE
More page list tweak ideas

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/AdminThemeUikit#41]
Hi Ryan - a few ideas:

1. make the new > prefix arrow a little darker so it's more obvious which pages have children, or maybe a "badge" style icon for the number of children would help highlight these?
2. make the text color for those with children different (so we know it's worth clicking on)
3. inline with 2 above, maybe remove the href from pages with no children - I know this used to be used to show page action buttons, but now we have them show on hover, this is now just confusing
4. Why does clicking on a page highlight the row, eg the "Aera_hoffman" and "5 process story" rows? I think highlighting on hover and also on a page when it's children are open makes sense, but I don't understand this current behavior

![screen shot 2017-10-06 at 7 56 11 am](https://user-images.githubusercontent.com/871211/31284195-bb62fe9c-aa6c-11e7-8f97-9a177733c29a.png)

**Comment by ryancramerdesign** [comment]
> make the new > prefix arrow a little darker so it's more obvious which pages have children

Since the icon isn't technically necessary, I'm reluctant to give it much importance by making it dark. Though maybe it's my screen, it's quite visible as-is, but will try on some other screens. Sometimes these things are quite visible in one case and nearly invisible in another, in which case it's better just to make sure they are visible on both even if a bit too dark on one of them. 

> maybe a "badge" style icon for the number of children would help highlight these?

I like the idea, but I think a badge might be too prominent. I prefer to stick with the current counts, consistent with what we've always had, but may experiment and test things out just to see. 

> make the text color for those with children different (so we know it's worth clicking on)

I also like this idea, and will experiment. Though since a change in color already indicates hidden vs. non-hidden, I'm a little worried about muddying that. There is already a children count, plus the new angle icons, to indicate that children are present, so doesn't seem like it's really necessary to do even more. Will experiment though. 

Another thing to note is that a page is worth clicking on whether it's got children or not. As always a clicked page is one that's "open", whether there are children or not. An open page is one that can have other pages dragged in as children (through Move operations). I use it regularly, but am guessing the need is not all that common for most. 

> Why does clicking on a page highlight the row, eg the "Aera_hoffman" and "5 process story" rows?

See above.

**Comment by gmclelland** [comment]
> make the new > prefix arrow a little darker so it's more obvious which pages have children, or maybe a "badge" style icon for the number of children would help highlight these?

Maybe something like this?
![badges](https://user-images.githubusercontent.com/40570/32378752-981c411e-c079-11e7-80ec-2dc401e0a7ed.jpg)

I believe the code I used is:
```css
.PageList .PageListItem .PageListNumChildren:after {
    content: "";
    height: 0;
    border-left: 5px solid transparent;
    border-right: 5px solid transparent;
    border-top: 5px solid #c8d2da;
    position: relative;
    top: 11px;
    left: 2px;
}

.detail, .notes, .pw-detail, .pw-notes {
    font-size: .875rem;
    line-height: 1.5;
    color: #8d939e !important;
    color: #c2cdda !important;
    background: #FAFBFC;
    padding: 2px 8px 2px 5px !important;
    margin-left: .25em;
}
```

The thing I noticed with that CSS code is that there is always a span.PageListNumChildren element printed even if there isn't any children.  When you give that span a background it will always be shown if there isn't any children.
