### ISSUE TITLE
Firefox - in the flyout side menu - arrows aren't aligned

### ISSUE THREAD

**Issue by gmclelland** [ryancramerdesign/AdminThemeUikit#42]
![edit page about us pwoliver dev 2017-10-06 14-29-05](https://user-images.githubusercontent.com/40570/31295114-e910ef4e-aaa2-11e7-8dde-f3e88be3571d.jpg)

**Comment by gmclelland** [comment]
Disabling this rule fixes the arrow's vertical alignment:
```css
.pw-sidebar-nav > li a {
    white-space: nowrap;
}
```
